2025-03-04 19:53:41,753 INFO    MainThread:4792 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-04 19:53:41,753 INFO    MainThread:4792 [wandb_setup.py:_flush():67] Configure stats pid to 4792
2025-03-04 19:53:41,754 INFO    MainThread:4792 [wandb_setup.py:_flush():67] Loading settings from C:\Users\jaygu\.config\wandb\settings
2025-03-04 19:53:41,754 INFO    MainThread:4792 [wandb_setup.py:_flush():67] Loading settings from F:\Semester 8\Introduction to Deep Learning\Assignment_1\wandb\settings
2025-03-04 19:53:41,754 INFO    MainThread:4792 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-04 19:53:41,754 INFO    MainThread:4792 [wandb_init.py:setup_run_log_directory():647] Logging user logs to F:\Semester 8\Introduction to Deep Learning\Assignment_1\wandb\run-20250304_195341-qh5ygpyr\logs\debug.log
2025-03-04 19:53:41,754 INFO    MainThread:4792 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to F:\Semester 8\Introduction to Deep Learning\Assignment_1\wandb\run-20250304_195341-qh5ygpyr\logs\debug-internal.log
2025-03-04 19:53:41,755 INFO    MainThread:4792 [wandb_init.py:init():761] calling init triggers
2025-03-04 19:53:41,755 INFO    MainThread:4792 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'hidden_size': 64, 'learning_rate': 0.001, 'num_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'xavier_normal'}
config: {'epochs': 5, 'batch_size': 32, 'eval_freq': 1, 'learning_rate': 0.001, 'dataset': 'mnist', 'hidden_size': 64, 'num_layers': 5, 'optimizer': 'adam', 'weight_init': 'xavier_normal', 'activation': 'relu', 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-08, 'momentum': 0.9, 'weight_decay': 0.0005, 'wandb_project': 'Multilayer_FeedForward_Network', 'wandb_entity': 'jay_gupta-indian-institute-of-technology-madras', 'beta': 0.9, 'loss': 'cross_entropy', '_wandb': {}}
2025-03-04 19:53:41,755 INFO    MainThread:4792 [wandb_init.py:init():784] starting backend
2025-03-04 19:53:41,755 INFO    MainThread:4792 [wandb_init.py:init():788] sending inform_init request
2025-03-04 19:53:41,775 INFO    MainThread:4792 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-04 19:53:41,776 INFO    MainThread:4792 [wandb_init.py:init():803] backend started and connected
2025-03-04 19:53:41,777 INFO    MainThread:4792 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'relu', 'batch_size': 32, 'hidden_size': 64, 'learning_rate': 0.001, 'num_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'xavier_normal'}
2025-03-04 19:53:41,780 INFO    MainThread:4792 [wandb_init.py:init():896] updated telemetry
2025-03-04 19:53:41,825 INFO    MainThread:4792 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-04 19:53:42,687 INFO    MainThread:4792 [wandb_init.py:init():995] starting run threads in backend
2025-03-04 19:53:48,497 INFO    MainThread:4792 [wandb_run.py:_console_start():2377] atexit reg
2025-03-04 19:53:48,498 INFO    MainThread:4792 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-04 19:53:48,498 INFO    MainThread:4792 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-04 19:53:48,498 INFO    MainThread:4792 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-04 19:53:48,503 INFO    MainThread:4792 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-04 19:54:20,721 WARNING MsgRouterThr:4792 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\lib\sock_client.py", line 258, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\lib\sock_client.py", line 262, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-04 19:54:20,725 INFO    MsgRouterThr:4792 [mailbox.py:close():115] Closing mailbox, abandoning 3 handles.
